on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - run: go build
      - run: zip action-gh-release-test.zip action-gh-release-test
      - uses: softprops/action-gh-release@v1
        with:
          files: action-gh-release-test.zip
          draft: true
          generate_release_notes: true
